### PR TITLE
docs: Imporve wording

### PR DESCRIPTION
**Pull request by JohnTitor**
r? @JohnTitor

### CODE REVIEW

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:warning: Forbid to merge by label `S-do-not-merge`

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 1fe7bf951a6c4285e371b8a16be25f2629cbd8df has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: 1fe7bf951a6c4285e371b8a16be25f2629cbd8df has been merged into the auto branch 043c26ee7d30e2ff64292d7dd85fc3b315071288

**Comment by JohnTitor** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `JohnTitor`

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:hourglass: 1fe7bf951a6c4285e371b8a16be25f2629cbd8df has been merged into the auto branch 043c26ee7d30e2ff64292d7dd85fc3b315071288

**Comment by JohnTitor** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:collision: The result of what tried to merge this pull request is `error`.

* [The Travis CI build is in progress](https://travis-ci.org/JohnTitor/tsuncon/builds/486575765?utm_source=github_status&utm_medium=notification)

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `JohnTitor`

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:warning: Forbid to merge by label `S-do-not-merge`

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by JohnTitor** [comment]
this test is done

**Pull request closed without merging**
