### PR TITLE
Deploy by CircleCI

### PR DESCRIPTION
**Pull request by JohnTitor**

### CODE REVIEW

**Comment by KoujiroFrau** [comment]
:eggplant: I picked a reviewer randomly, you can use `r?` to overwrite.

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 6b692f4ebb70fea4b3595f53290c0f539829ca51 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: 6b692f4ebb70fea4b3595f53290c0f539829ca51 has been merged into the auto branch d7103af64492b7d6e9c61dc279d93a21620791de

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build is in progress](https://travis-ci.org/JohnTitor/tsuncon/builds/508275639?utm_source=github_status&utm_medium=notification)
* [Your tests passed on CircleCI!](https://circleci.com/gh/JohnTitor/tsuncon/39?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Pull request merged**
