### PR TITLE
docs: Add option

### PR DESCRIPTION
**Pull request by JohnTitor**
r? @JohnTitor

### CODE REVIEW

**Comment by JohnTitor** [comment]
@KoujiroFrau r=super-unknown-no-exist-user-hoge-hoge

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 8b2c44b72cd4ca92cc41eb71d86570961196b441 has been approved by `super-unknown-no-exist-user-hoge-hoge`

**Comment by KoujiroFrau** [comment]
:hourglass: 8b2c44b72cd4ca92cc41eb71d86570961196b441 has been merged into the auto branch 2ac017414650453dfab93b04ebcc936a0bc1babc

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build is in progress](https://travis-ci.org/JohnTitor/tsuncon/builds/504201531?utm_source=github_status&utm_medium=notification)
* [Your tests passed on CircleCI!](https://circleci.com/gh/JohnTitor/tsuncon/30?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Pull request merged**
