### PR TITLE
test: Remove config

### PR DESCRIPTION
**Pull request by JohnTitor**

### CODE REVIEW

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by JohnTitor** [comment]
@KoujiroFrau r=JohnTitor

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit dba673155a909fb915488ecd012548ff0b592016 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: dba673155a909fb915488ecd012548ff0b592016 has been merged into the auto branch bf2421550c2a27875c6a8cc0d5a4912ac86d944a

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/JohnTitor/tsuncon/builds/484171145?utm_source=github_status&utm_medium=notification)

**Pull request merged**
