### PR TITLE
test: Remove branch config

### PR DESCRIPTION
**Pull request by JohnTitor**
r? @JohnTitor

### CODE REVIEW

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit b3764afb3bf7e485449556f4a81667e4b5fe0369 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: b3764afb3bf7e485449556f4a81667e4b5fe0369 has been merged into the auto branch 2acccee02e9afe4363172df9bbb9bd9aed3d161a

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build is in progress](https://travis-ci.org/JohnTitor/tsuncon/builds/495042076?utm_source=github_status&utm_medium=notification)
* [Your tests passed on CircleCI!](https://circleci.com/gh/JohnTitor/tsuncon/11?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Pull request merged**
