### PR TITLE
docs: Add year

### PR DESCRIPTION
**Pull request by JohnTitor**

### CODE REVIEW

**Comment by KoujiroFrau** [comment]
:eggplant: I picked a reviewer randomly, you can use `r?` to overwrite.

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit ce09f5c70e7808a08dc5e056ef2d2dfab562bc63 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: ce09f5c70e7808a08dc5e056ef2d2dfab562bc63 has been merged into the auto branch f2c5ecdd1d188628a5931efb68acce6c75caee43

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit ce09f5c70e7808a08dc5e056ef2d2dfab562bc63 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: ce09f5c70e7808a08dc5e056ef2d2dfab562bc63 has been merged into the auto branch f2c5ecdd1d188628a5931efb68acce6c75caee43

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit ce09f5c70e7808a08dc5e056ef2d2dfab562bc63 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: ce09f5c70e7808a08dc5e056ef2d2dfab562bc63 has been merged into the auto branch f2c5ecdd1d188628a5931efb68acce6c75caee43

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit ce09f5c70e7808a08dc5e056ef2d2dfab562bc63 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: ce09f5c70e7808a08dc5e056ef2d2dfab562bc63 has been merged into the auto branch f2c5ecdd1d188628a5931efb68acce6c75caee43

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit ce09f5c70e7808a08dc5e056ef2d2dfab562bc63 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: ce09f5c70e7808a08dc5e056ef2d2dfab562bc63 has been merged into the auto branch f2c5ecdd1d188628a5931efb68acce6c75caee43

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [Your tests passed on CircleCI!](https://circleci.com/gh/JohnTitor/tsuncon/27?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
* [The Travis CI build passed](https://travis-ci.org/JohnTitor/tsuncon/builds/503674367?utm_source=github_status&utm_medium=notification)

**Pull request merged**
