### PR TITLE
docs: Add year

### PR DESCRIPTION
**Pull request by JohnTitor**
r? @JohnTitor

### CODE REVIEW

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 106218cc7d8d78b394af08dd9991aefca470dcd2 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: 106218cc7d8d78b394af08dd9991aefca470dcd2 has been merged into the auto branch 0dd19514ab49a4a238cd0fa5604a85efbb5027a5

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build is in progress](https://travis-ci.org/JohnTitor/tsuncon/builds/503006501?utm_source=github_status&utm_medium=notification)
* [Your tests passed on CircleCI!](https://circleci.com/gh/JohnTitor/tsuncon/24?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Pull request merged**
