### PR TITLE
docs: Remove unnecessary dollar signs

### PR DESCRIPTION
**Pull request by JohnTitor**
r? @JohnTitor

### CODE REVIEW

**Comment by JohnTitor** [comment]
@KoujiroFrau r=me

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 41c10bccfb802d05b6f6bbb1a4fd681ccc53f67c has been approved by JohnTitor

**Comment by KoujiroFrau** [comment]
:hourglass: 41c10bccfb802d05b6f6bbb1a4fd681ccc53f67c has been merged into the auto branch 99a7254f36c66eae58f46237b0e4f5e1b323b580

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/JohnTitor/tsuncon/builds/495037235?utm_source=github_status&utm_medium=notification)

**Pull request merged**
