### PR TITLE
chore: fix typo

### PR DESCRIPTION
**Pull request by JohnTitor**

### CODE REVIEW

**Comment by KoujiroFrau** [comment]
:eggplant: I picked a reviewer randomly, you can use `r?` to overwrite.

**Comment by JohnTitor** [comment]
@KoujiroFrau r=me

**Comment by KoujiroFrau** [comment]
:no_entry: `me` isn't included in OWNERS.json as a reviewer

**Comment by KoujiroFrau** [comment]
:pushpin: Commit e9d1f3a6e58c34fe3129ffe2b32fa0877be33c58 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: e9d1f3a6e58c34fe3129ffe2b32fa0877be33c58 has been merged into the auto branch ae1e3eb90acf8da6afea5b2b27c97aefe737db90

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [Your tests passed on CircleCI!](https://circleci.com/gh/JohnTitor/tsuncon/42?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
* [The Travis CI build is in progress](https://travis-ci.org/JohnTitor/tsuncon/builds/508279714?utm_source=github_status&utm_medium=notification)

**Pull request merged**
