### PR TITLE
docs: Add badge

### PR DESCRIPTION
**Pull request by JohnTitor**

### CODE REVIEW

**Comment by KoujiroFrau** [comment]
:eggplant: I picked a reviewer randomly, you can use `r?` to overwrite.

**Comment by JohnTitor** [comment]
@KoujiroFrau r=hhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by JohnTitor** [comment]
@KoujiroFrau r=hhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by KoujiroFrau** [comment]
:: `hhhhhhhhhhhhhhhhhhhhhhhhhh` isn't included reviewers in OWNERS.json

**Comment by JohnTitor** [comment]
Okay, I'll merge

**Pull request merged**
