### PR TITLE
Fix config

### PR DESCRIPTION
**Pull request by JohnTitor**

### CODE REVIEW

**Comment by KoujiroFrau** [comment]
:eggplant: I picked a reviewer randomly, you can use `r?` to overwrite.

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit c0999abfd3c6223fe94ac34d7eee9fc93fd0226b has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: c0999abfd3c6223fe94ac34d7eee9fc93fd0226b has been merged into the auto branch c9ae4465198c5805f7f27e91031277eaeec0a3c6

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build is in progress](https://travis-ci.org/JohnTitor/tsuncon/builds/508284113?utm_source=github_status&utm_medium=notification)
* [Your tests passed on CircleCI!](https://circleci.com/gh/JohnTitor/tsuncon/46?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Pull request merged**
