### PR TITLE
minor: ningen ha oroka

### PR DESCRIPTION
**Pull request by AjimuNajimi**

### CODE REVIEW

**Comment by KoujiroFrau** [comment]
:pushpin: Commit f36520f0b1cd26c568a961841eacb1b1f6a11b9a has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: f36520f0b1cd26c568a961841eacb1b1f6a11b9a has been merged into the auto branch 2248a52d9c64c6837897cc8bc34838f0187e9050

**Comment by JohnTitor** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build is in progress](https://travis-ci.org/JohnTitor/tsuncon/builds/498297491?utm_source=github_status&utm_medium=notification)
* [Your tests passed on CircleCI!](https://circleci.com/gh/JohnTitor/tsuncon/14?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Pull request merged**
